# Generated by Django 5.0.7 on 2024-09-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to='profile-pics'),
        ),
    ]
